### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ghost**
Made a few improvements to the class:
* Removed Linq dependancy
* Changed class name to avoid namespace confusion
* Added the ability to select a different Animator component than one on the holding GameObject (useful to place responding code into another component than the one actually playing the animation)

### CODE REVIEW

**Comment by paulhayes** [comment]
Hi Chris.

Thanks for an update to this library. I think these are some good changes. However I can't accept the class name change. Can you change the main class name back and do a new pull request, and I'll be more than happy to accept.

Yours
Paul

**Comment by ghost** [comment]
I've renamed the class back to its former name. I was pretty sure you would not accept this.

However, this remains a serious issue, as the only solution to avoid having to type each and every time AnimatorStateMachineUtil.AnimatorStateMachineUtil to refer to the class is to use an alias using such as `using FSMUtil = AnimatorStateMachineUtil.AnimatorStateMachineUtil;`

**Comment by ghost** [comment]
@paulhayes I've updated this PR directly. I guess it is enough but if you really need a new PR, I can do that.

**Comment by paulhayes** [comment]
You make a compelling argument @chrisCheeseBurgames. I think I'll change the namespace to AnimatorStateMachine. I'm just loathed to change the monobehaviour name as it creates a silent issue in peoples scenes if they update, as the reference gets lost.

Oh I can't do that, because that's what Unity called there class! You know I wrote this library before they made that eons ago!

How about AnimatorStateMachineLibrary?

**Comment by ghost** [comment]
AnimatorStateMachineLibrary seems good to me for the namespace. You're right, it's the best solution.

**Pull request merged**
